### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 687766616e** [h4ckzard/wpseyes#2]
`>> crack`
```
Traceback (most recent call last):
  File "wpseyes.py", line 250, in <module>
    WpsEyes().cmdloop()
  File "/usr/lib/python3.7/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.7/cmd.py", line 217, in onecmd
    return func(arg)
  File "wpseyes.py", line 198, in do_crack
    line = arg[0]
IndexError: list index out of range
```

**Comment by h4ckzard** [comment]
Thanks you for issue :+1:

**Comment by h4ckzard** [comment]
Fixed
